<?php
$pageTitle = 'Áreas'; require_once __DIR__ . '/includes/header.php';
$edit = ['id'=>'','nome'=>'','lugares'=>'','imagem'=>null,'status'=>'ativo'];
if (isset($_GET['editar'])) { $s=$pdo->prepare('SELECT * FROM areas WHERE id=?'); $s->execute([(int)$_GET['editar']]); $edit=$s->fetch() ?: $edit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try { $id=(int)($_POST['id']??0); $nome=trim($_POST['nome']??''); $lugares=trim($_POST['lugares']??''); if ($nome===''||$lugares==='') throw new RuntimeException('Preencha nome e quantidade de lugares.'); $image=upload_image($_FILES['imagem']??[], $_POST['imagem_atual']??null); $status=$_POST['status']==='oculto'?'oculto':'ativo';
        $before = $id ? history_snapshot($pdo, 'area', $id) : [];
        if ($id) $pdo->prepare('UPDATE areas SET nome=?, lugares=?, imagem=?, status=? WHERE id=?')->execute([$nome,$lugares,$image,$status,$id]); else $pdo->prepare('INSERT INTO areas (nome,lugares,imagem,status) VALUES (?,?,?,?)')->execute([$nome,$lugares,$image,$status]);
        $id = $id ?: (int) $pdo->lastInsertId();
        history_log($pdo, 'area', $id, $before, history_snapshot($pdo, 'area', $id));
        flash('success','Área salva com sucesso.'); redirect('areas.php');
    } catch (Throwable $e) { flash('error',$e->getMessage()); }
}
if (isset($_GET['toggle'])) { $toggleId=(int)$_GET['toggle']; $before=history_snapshot($pdo,'area',$toggleId); $pdo->prepare("UPDATE areas SET status=IF(status='ativo','oculto','ativo') WHERE id=?")->execute([$toggleId]); history_log($pdo,'area',$toggleId,$before,history_snapshot($pdo,'area',$toggleId)); flash('success','Status da área atualizado.'); redirect('areas.php'); }
$areas=$pdo->query('SELECT * FROM areas ORDER BY nome')->fetchAll();
?><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Áreas</h1><p class="text-muted mb-0">Ambientes disponíveis para reserva</p></div></div><div class="row g-4"><div class="col-lg-4"><section class="app-card" id="form-area"><h2 class="h5 mb-3"><?= $edit['id']?'Editar área':'Cadastrar área' ?></h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?= e($edit['id']) ?>"><input type="hidden" name="imagem_atual" value="<?= e($edit['imagem']) ?>"><div class="mb-3"><label class="form-label">Nome da Área</label><input class="form-control" name="nome" required value="<?= e($edit['nome']) ?>"></div><div class="mb-3"><label class="form-label">Quantidade de Lugares</label><input class="form-control" name="lugares" required value="<?= e($edit['lugares']) ?>"></div><div class="mb-3"><label class="form-label">Imagem</label><input class="form-control" type="file" name="imagem" accept="image/jpeg,image/png,image/webp"></div><div class="mb-4"><label class="form-label">Status</label><select class="form-select" name="status"><option value="ativo" <?= $edit['status']==='ativo'?'selected':'' ?>>Ativo</option><option value="oculto" <?= $edit['status']==='oculto'?'selected':'' ?>>Oculto</option></select></div><button class="btn btn-gold" type="submit">Salvar</button><?php if($edit['id']): ?><a class="btn btn-link" href="areas.php">Cancelar</a><?php endif; ?></form></section></div><div class="col-lg-8"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Imagem</th><th>Área</th><th>Lugares</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($areas as $area): ?><tr><td><?php if($area['imagem']): ?><img class="area-thumb" src="uploads/<?= e($area['imagem']) ?>" alt=""><?php endif; ?></td><td class="fw-semibold"><?= e($area['nome']) ?></td><td><?= e($area['lugares']) ?></td><td><span class="badge text-bg-<?= $area['status']==='ativo'?'success':'secondary' ?> badge-status"><?= e($area['status']) ?></span></td><td class="text-end"><div class="group-actions"><a class="btn btn-sm btn-action btn-action-edit" href="areas.php?editar=<?= $area['id'] ?>">Editar</a><a class="btn btn-sm btn-action btn-action-hide" href="areas.php?toggle=<?= $area['id'] ?>"><?= $area['status']==='ativo'?'Ocultar':'Ativar' ?></a></div></td></tr><?php endforeach; ?></tbody></table></div></div></div><?php require __DIR__ . '/includes/footer.php';
