<?php
$pageTitle='Cancelar reserva'; require_once __DIR__ . '/includes/header.php';
$id=(int)($_GET['id']??$_POST['id']??0);$s=$pdo->prepare("SELECT r.*,g.nome grupo,COALESCE((SELECT GROUP_CONCAT(sg.nome ORDER BY sg.nome SEPARATOR ', ') FROM subgrupos sg WHERE FIND_IN_SET(sg.id, r.subgrupos_ids)), sg2.nome) subgrupo,COALESCE(a.nome, 'Todas as áreas') area,a.imagem FROM reservas r JOIN grupos g ON g.id=r.grupo_id JOIN subgrupos sg2 ON sg2.id=r.subgrupo_id LEFT JOIN areas a ON a.id=r.area_id WHERE r.id=?");$s->execute([$id]);$reservation=$s->fetch();if(!$reservation)redirect('index.php');
$selectedAreaIds=[]; if(!empty($reservation['areas_ids'])){ $selectedAreaIds = array_values(array_unique(array_filter(array_map('intval', explode(',', $reservation['areas_ids']))))); }
$reservationAreaName = $reservation['area'];
$reservationImage = $reservation['imagem'];
if (count($selectedAreaIds) > 1) {
	$reservationAreaName = 'Várias áreas';
	$reservationImage = 'if1im5if1im5if1.jpeg';
}
if($_SERVER['REQUEST_METHOD']==='POST'){ $by=$_SESSION['usuario_nome']??'';$reason=trim($_POST['motivo_cancelamento']??'');$scope=$_POST['scope']??'this';if($by===''||$reason==='')flash('error','Não foi possível identificar o usuário logado ou o motivo.');else{if(!empty($reservation['serie_id']) && $scope==='series'){$pdo->prepare("UPDATE reservas SET status='cancelado',cancelado_por=?,motivo_cancelamento=? WHERE serie_id=?")->execute([$by,$reason,$reservation['serie_id']]);}else{$pdo->prepare("UPDATE reservas SET status='cancelado',cancelado_por=?,motivo_cancelamento=? WHERE id=?")->execute([$by,$reason,$id]);}flash('success','Reserva cancelada e mantida para auditoria.');redirect('index.php');}}
$start=new DateTimeImmutable($reservation['data_inicio']);$end=new DateTimeImmutable($reservation['data_fim']);$weekdays=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];$duration=$reservation['dia_inteiro']?'dia todo':(($end->getTimestamp()-$start->getTimestamp())/60).' min';$recurrence=$reservation['recorrencia']==='nenhuma'?'Não recorrente':'Recorrente: '.ucfirst($reservation['recorrencia']);
?><div class="row justify-content-center"><div class="col-lg-9"><div class="app-card"><h1 class="h3">Cancelar reserva</h1><div class="reservation-summary"><span class="reservation-summary-label">Resumo</span><div class="reservation-summary-area"><?php if($reservationImage): ?><img class="reservation-summary-image" src="uploads/<?= e($reservationImage) ?>" alt="<?= e($reservationAreaName) ?>"><?php else: ?><span class="reservation-summary-placeholder">Área</span><?php endif; ?><strong class="reservation-summary-area-name"><?= e($reservationAreaName) ?></strong></div><div class="reservation-summary-details"><h2 class="reservation-summary-group"><?= e($reservation['grupo']) ?></h2><p class="reservation-summary-subgroup"><?= e($reservation['subgrupo']) ?></p><div class="reservation-summary-meta"><span class="summary-date"><?= ucfirst($weekdays[(int)$start->format('w')]) ?>: <strong><?= $start->format('d/m/y') ?></strong></span><span class="summary-time">Início: <strong><?= $start->format('H:i') ?></strong></span><span class="summary-duration">Duração: <strong><?= e($duration) ?></strong></span><span class="summary-recurrence"><?= e($recurrence) ?></span></div></div></div><?php if($reservation['status']==='cancelado'): ?><div class="alert alert-secondary">Esta reserva já foi cancelada.</div><?php else: ?><form method="post"><input type="hidden" name="id" value="<?= $id ?>"><?php if(!empty($reservation['serie_id'])): ?><div class="mb-3"><label class="form-label">Escopo do cancelamento</label><div class="form-check"><input class="form-check-input" type="radio" name="scope" id="cancelThis" value="this" checked><label class="form-check-label" for="cancelThis">Cancelar apenas esta ocorrência</label></div><div class="form-check"><input class="form-check-input" type="radio" name="scope" id="cancelSeries" value="series"><label class="form-check-label" for="cancelSeries">Cancelar toda a recorrência</label></div></div><?php endif; ?><p class="text-muted small">Cancelando como: <strong><?= e($_SESSION['usuario_nome']) ?></strong></p><div class="mb-4"><label class="form-label">Motivo do cancelamento</label><textarea class="form-control" name="motivo_cancelamento" rows="4" required></textarea></div><button class="btn btn-danger">Confirmar cancelamento</button><a class="btn btn-outline-secondary" href="reserva_form.php?id=<?= $id ?>">Voltar</a></form><?php endif; ?></div></div></div><?php require __DIR__.'/includes/footer.php';
